// Project info
#define WFE_EDITOR_PROJECT_NAME "Wireframe-Engine"

#define WFE_EDITOR_PROJECT_VERSION_MAJOR 0
#define WFE_EDITOR_PROJECT_VERSION_MINOR 1
#define WFE_EDITOR_PROJECT_VERSION_PATCH 0
#define WFE_EDITOR_PROJECT_VERSION_TWEAK 0
